name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject environment variables
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          sed -i 's/process\.env\.HF_API_KEY/"'$HF_API_KEY'"/' script.js
          sed -i 's/process\.env\.HF_API_KEY/"'$HF_API_KEY'"/' script1.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./code/html
